@base_url = http://localhost:5144/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Nicoly",
    "cpf" : "12345678912"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 100,
    "mes" : 10,
    "ano" : 2023
}

### Obtenção de todas as folhas
GET {{base_url}}/folha/listar

### Obtenção de uma folha
GET {{base_url}}/folha/buscar/10/2023